-- This script will be generated by Prisma migrations
-- Run: npm run db:push or npx prisma db push
-- This will create all tables based on the schema.prisma file

-- After running the Prisma command, execute the init-data.sql script
